-- =============================================
-- Tabela: webhook_logs
-- Propósito: Armazenar leads recebidos via webhook
-- =============================================

-- Cria a tabela (se não existir)
CREATE TABLE IF NOT EXISTS public.webhook_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cnpj TEXT,
    empresa TEXT,
    nome_decisor TEXT,
    cargo TEXT,
    telefone TEXT,
    email_empresa_original TEXT,
    email_gerado TEXT,
    email_sugerido TEXT,
    dominio TEXT,
    municipio TEXT,
    uf TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Habilita Row Level Security (RLS)
ALTER TABLE public.webhook_logs ENABLE ROW LEVEL SECURITY;

-- Política: permite INSERT de qualquer usuário (útil para webhooks com anon key)
-- Se você usar service_role_key, esta política NÃO é necessária para escrita,
-- mas mantemos para flexibilidade.
CREATE POLICY "Permitir inserção pública na webhook_logs"
ON public.webhook_logs
FOR INSERT
TO anon, authenticated
WITH CHECK (true);

-- Política: permite leitura apenas para authenticated (ou remova se quiser anon ler)
CREATE POLICY "Permitir leitura apenas para usuários autenticados"
ON public.webhook_logs
FOR SELECT
TO authenticated
USING (true);

-- Opcional: se quiser que o 'anon' também possa ler (não recomendado para dados sensíveis)
-- CREATE POLICY "Permitir leitura pública" 
-- ON public.webhook_logs 
-- FOR SELECT 
-- TO anon 
-- USING (true);

-- Concede permissões mínimas
GRANT USAGE ON SCHEMA public TO anon, authenticated;
GRANT INSERT ON public.webhook_logs TO anon;
GRANT SELECT ON public.webhook_logs TO authenticated;
GRANT USAGE ON SEQUENCE public.webhook_logs_id_seq TO anon;
